name: Ubuntu-implicits
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/base.yml
    with:
      compiler: "ocaml-variants.4.02.1+modular-implicits"
      os: "ubuntu-latest"
